//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelivieryMethod
    {
        public byte Id { get; set; }
        public string DelivieryName { get; set; }
        public string DelivieryNameDisplay { get; set; }
        public string DeliveryCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
