//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleScreenDetail
    {
        public int Id { get; set; }
        public int ModuleScreenId { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public string State { get; set; }
        public string Route { get; set; }
        public string ModuleScreenClass { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    }
}
