//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public byte Id { get; set; }
        public string StatusName { get; set; }
        public string StatusDisplay { get; set; }
        public string Image { get; set; }
        public string Type { get; set; }
    }
}
