//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPickupDetail
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> OrderDesignDetailId { get; set; }
        public Nullable<int> SectionDetailID { get; set; }
        public Nullable<int> ProductSKUID { get; set; }
        public Nullable<int> RequiredQty { get; set; }
        public Nullable<int> PickedQty { get; set; }
    
        public virtual ProductSKU ProductSKU { get; set; }
        public virtual SectionDetail SectionDetail { get; set; }
        public virtual Order Order { get; set; }
    }
}
