//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStrikeOffLogo
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> OrderEmblishmentID { get; set; }
        public string Logo { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> RevisionNo { get; set; }
    }
}
