//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderCartons = new HashSet<OrderCarton>();
            this.OrderPickupDetails = new HashSet<OrderPickupDetail>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string OrderNumber { get; set; }
        public string PONumber { get; set; }
        public string OrderType { get; set; }
        public string OrderNote { get; set; }
        public string OrderName { get; set; }
        public string JobSheetFile { get; set; }
        public string JobSheetShippingDetailFile { get; set; }
        public byte OrderStatusId { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> OrderAddressId { get; set; }
        public Nullable<int> SalesCordinator { get; set; }
        public Nullable<int> Mechandiser { get; set; }
        public Nullable<int> WarehouseUserId { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryOnUtc { get; set; }
        public Nullable<System.DateTime> PickupRequestedOnUtc { get; set; }
        public Nullable<System.DateTime> DispatchedOnUtc { get; set; }
        public string PickupNoteFile { get; set; }
        public string UpdatedPickupNoteFile { get; set; }
        public string DispatchNoteFile { get; set; }
        public Nullable<byte> DelivieryMethodId { get; set; }
        public Nullable<int> ModifyDays { get; set; }
        public Nullable<System.DateTime> RequestedDeliveryDate { get; set; }
        public Nullable<System.DateTime> RequestedExFactoryDate { get; set; }
        public Nullable<System.DateTime> ConfirmedExFactoryDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCarton> OrderCartons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPickupDetail> OrderPickupDetails { get; set; }
    }
}
