//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDesignDetail
    {
        public int Id { get; set; }
        public int OrderDesignId { get; set; }
        public string PlayerName { get; set; }
        public string PlayerNumber { get; set; }
        public short Quantity { get; set; }
        public int ProductSKUId { get; set; }
        public Nullable<short> PickedQuantity { get; set; }
    }
}
