//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEmblishment
    {
        public int Id { get; set; }
        public int OrderDesignId { get; set; }
        public string EmblishmentType { get; set; }
        public string PrintMethod { get; set; }
        public string LogoImage { get; set; }
        public Nullable<decimal> LogoWidth { get; set; }
        public Nullable<decimal> LogoHeight { get; set; }
        public Nullable<bool> IsAspectRatio { get; set; }
        public string DimensionUnit { get; set; }
        public string Color { get; set; }
        public string FontFamily { get; set; }
    }
}
