//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDesign
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string DesignName { get; set; }
        public string DesignNumber { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string ProductDesignImage { get; set; }
        public string ProductColor { get; set; }
        public string JobSeetImage { get; set; }
        public string JobSeetFile { get; set; }
        public bool IsDeafultLogo { get; set; }
        public string PickFormFIle { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<byte> OrderDesignStatusId { get; set; }
    }
}
