//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStyle
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string StyleCode { get; set; }
        public string StyleName { get; set; }
        public string StyleThumbnail { get; set; }
        public string ThreeDStyleObj { get; set; }
        public byte SectionNumber { get; set; }
        public bool IsUploadLogo { get; set; }
        public bool IsText { get; set; }
    }
}
