//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSKU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSKU()
        {
            this.OrderCartonDetails = new HashSet<OrderCartonDetail>();
            this.OrderPickupDetails = new HashSet<OrderPickupDetail>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string SKU { get; set; }
        public byte SizeId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public string Style { get; set; }
        public decimal Weight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<int> ActualQuantity { get; set; }
        public Nullable<int> ExpectedQuantity { get; set; }
        public Nullable<int> WarningLevel { get; set; }
        public string OriginalJob { get; set; }
        public string FebricNo { get; set; }
        public string FebricDescription { get; set; }
        public string ProductDescription { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
        public string HSCode { get; set; }
        public string LanguageDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCartonDetail> OrderCartonDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPickupDetail> OrderPickupDetails { get; set; }
    }
}
