//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatagory
    {
        public byte Id { get; set; }
        public string CatagoryName { get; set; }
        public string CatagoryDisplay { get; set; }
        public int CustomerId { get; set; }
    }
}
