//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public int Id { get; set; }
        public Nullable<byte> ProductCatagoryId { get; set; }
        public int StockRangeId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string ProductDescription { get; set; }
        public string LogoThumbnail { get; set; }
        public string ThreeDModelObjFile { get; set; }
        public bool IsUpperArmRight { get; set; }
        public bool IsLowerArmRight { get; set; }
        public bool IsUpperArmLeft { get; set; }
        public bool IsLowerArmLeft { get; set; }
        public bool IsChestCenterTop { get; set; }
        public bool IsRightChest { get; set; }
        public bool IsLeftChest { get; set; }
        public bool IsFrontMain { get; set; }
        public bool IsBackNeck { get; set; }
        public bool IsPlayerName { get; set; }
        public bool IsPlayerNumber { get; set; }
        public bool IsMidBack { get; set; }
        public bool IsLowerBack { get; set; }
        public bool IsLowerSleeveRight { get; set; }
        public bool IsLowerSleeveLeft { get; set; }
        public bool IsThighRight { get; set; }
        public bool IsThighLeft { get; set; }
        public bool IsBackThighLeft { get; set; }
        public bool IsBackThighRight { get; set; }
        public bool IsLeftShoulder { get; set; }
        public bool IsRightShoulder { get; set; }
        public bool IsSockFrontRight { get; set; }
        public bool IsSockFrontLeft { get; set; }
        public bool IsSockCalfLeft { get; set; }
        public bool IsSockCalfRight { get; set; }
        public bool IsUploadLogo { get; set; }
        public bool IsText { get; set; }
        public byte NumberOfSection { get; set; }
    }
}
