//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public byte ID { get; set; }
        public string size1 { get; set; }
        public string description { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string Type { get; set; }
    }
}
