//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStock
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ProductSKUId { get; set; }
        public System.DateTime UpdatedOnUtc { get; set; }
        public int UpdatedBy { get; set; }
    }
}
