//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserConfiguration
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string MailHostName { get; set; }
        public string SMTPport { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
        public string SMTPDisplayName { get; set; }
        public string FromMail { get; set; }
        public string EnableSsl { get; set; }
    }
}
