//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WMSEntities : DbContext
    {
        public WMSEntities()
            : base("name=WMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ModuleScreenDetail> ModuleScreenDetails { get; set; }
        public virtual DbSet<UserModuleScreen> UserModuleScreens { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserConfiguration> UserConfigurations { get; set; }
        public virtual DbSet<UserReceivingNote> UserReceivingNotes { get; set; }
        public virtual DbSet<UserReceivingNoteDetail> UserReceivingNoteDetails { get; set; }
        public virtual DbSet<UserStock> UserStocks { get; set; }
        public virtual DbSet<UserStockLog> UserStockLogs { get; set; }
        public virtual DbSet<WMSRole> WMSRoles { get; set; }
        public virtual DbSet<WMSUser> WMSUsers { get; set; }
        public virtual DbSet<WMSUserAdditional> WMSUserAdditionals { get; set; }
        public virtual DbSet<WMSUserAddress> WMSUserAddresses { get; set; }
        public virtual DbSet<WMSUserClaim> WMSUserClaims { get; set; }
        public virtual DbSet<WMSUserLogin> WMSUserLogins { get; set; }
        public virtual DbSet<WMSUserRole> WMSUserRoles { get; set; }
        public virtual DbSet<CommunicationLog> CommunicationLogs { get; set; }
        public virtual DbSet<OrderAddress> OrderAddresses { get; set; }
        public virtual DbSet<OrderCarton> OrderCartons { get; set; }
        public virtual DbSet<OrderCartonDetail> OrderCartonDetails { get; set; }
        public virtual DbSet<OrderDesign> OrderDesigns { get; set; }
        public virtual DbSet<OrderDesignDetail> OrderDesignDetails { get; set; }
        public virtual DbSet<OrderDesignStyle> OrderDesignStyles { get; set; }
        public virtual DbSet<OrderEmblishment> OrderEmblishments { get; set; }
        public virtual DbSet<OrderEmblishmentDetail> OrderEmblishmentDetails { get; set; }
        public virtual DbSet<OrderPickupDetail> OrderPickupDetails { get; set; }
        public virtual DbSet<OrderStrikeOffLogo> OrderStrikeOffLogos { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DelivieryMethod> DelivieryMethods { get; set; }
        public virtual DbSet<ModuleScreen> ModuleScreens { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Timezone> Timezones { get; set; }
        public virtual DbSet<ProductCatagory> ProductCatagories { get; set; }
        public virtual DbSet<ProductMaster> ProductMasters { get; set; }
        public virtual DbSet<ProductSKU> ProductSKUs { get; set; }
        public virtual DbSet<ProductStyle> ProductStyles { get; set; }
        public virtual DbSet<LineMaster> LineMasters { get; set; }
        public virtual DbSet<RowMaster> RowMasters { get; set; }
        public virtual DbSet<SectionDetail> SectionDetails { get; set; }
        public virtual DbSet<SectionMaster> SectionMasters { get; set; }
        public virtual DbSet<ShelfMaster> ShelfMasters { get; set; }
        public virtual DbSet<ShelfRowDetail> ShelfRowDetails { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
        public virtual DbSet<WarehouseAllocationDetail> WarehouseAllocationDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    
        public virtual ObjectResult<spGetOrderList_Result> spGetOrderList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetOrderList_Result>("spGetOrderList");
        }
    
        public virtual ObjectResult<spGetStockHeader_Result> spGetStockHeader(Nullable<int> customerId, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetStockHeader_Result>("spGetStockHeader", customerIdParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual int spGetUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetUser");
        }
    
        public virtual int spGetOrderListA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetOrderListA");
        }
    }
}
