//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Service.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMSUserAdditional
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> ManageUserId { get; set; }
        public string PaymentCurrency { get; set; }
        public string PaymentTerm { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<int> SalesUserId { get; set; }
        public Nullable<int> SalesCoOrdinatorId { get; set; }
        public Nullable<int> MerchandiseUserId { get; set; }
        public Nullable<int> WarehouseUserId { get; set; }
        public Nullable<int> ModifyDays { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string UserCode { get; set; }
    }
}
